### ISSUE TITLE
Couldn't train !

### ISSUE THREAD

**Issue by adanacademic** [dzhv/Spatio-Temporal-mobile-traffic-forecasting#2]
Hi, I am getting the following error: 

>   File "/usr/local/lib/python3.6/dist-packages/keras/layers/recurrent.py", line 2389, in _standardize_args
>     assert initial_state is None and constants is None
> AssertionError. 
it seems like system requirements mismatch, could you please show the Keras version?

**Comment by dzhv** [comment]
Hi.
Sadly, this is a bug with Keras, see here https://github.com/keras-team/keras/issues/9761#issuecomment-567915470  for more information.

I am not sure if this is fixed in the latest release.
However, when I was doing my research I had to download Keras source, make the modification mentioned in the link above and run `pip install . ` to register the local changes with conda / pip.

**Comment by adanacademic** [comment]
Thank you for your reply. I have tried different solutions but many other errors have raised. which Keras and tf versions have you used while this error happened.

**Comment by dzhv** [comment]
I had the following versions:
Keras 2.2.4
Tensorflow 1.13.1
