### ISSUE TITLE
Code looks like in it's raw form

### ISSUE THREAD

**Issue by saurabh1396** [dzhv/Spatio-Temporal-mobile-traffic-forecasting#3]
In the Notebooks folder - Arima.ipynb file

what's this - temp/save_{i}.pickle?
In [19]
saved = sm.load(f"temp/save_{i}.pickle")

what's this - where is this folder p1_d0_q0?
In [9]
save_path = "../results/arima/p1_d0_q0/saved_models"

what's this? - this func. def predict(model_fit, orders, inputs, output_length) - this function with 4 parameters - unspecified and errorsome.
def predict(model_fit, orders, inputs, output_length)

def predict(coef, history):

It could have been better if we have running code or no code at all.

**Comment by dzhv** [comment]
Hi. Sorry, you're right this particular notebook was left in a bit of a mess.  
If I remember correctly, this notebook is only for training and testing the ARIMA model (https://www.statsmodels.org/stable/generated/statsmodels.tsa.arima_model.ARIMA.html). It did not perform all that well for the problem, are you sure you need this notebook at all?

To answer your questions:

> what's this - temp/save_{i}.pickle?

My approach here was to train a separate ARIMA model for each point in the grid (i.e. for each grid cell in the city). To store the trained model, I was saving `grid size` * `grid size` number of files. This was done using the commented line in the 4th cell.
`#     model_fit.save(f"temp/save_{i}.pickle")`
The `saved = sm.load(f"temp/save_{i}.pickle")` line was used to load a specific ARIMA model for that specific grid cell.
However, something seems off as later on in the code the models are loaded from files in format `{save_path}/{x_coord}_{y_coord}.pickle`, so it seems that at some point I was saving them in that kind of format. 

> what's this - where is this folder p1_d0_q0?

This folder does not exist in the repo. Here, you should use the folder where you will store your ARIMA models. With something like `model_fit.save(f"{save_path}/{x_coord}_{y_coord}.pickle")`

> `func. def predict(model_fit, orders, inputs, output_length)`

It is specified in the 7th cell, but it seems that there are some indentations problems in the code, sorry.

> It could have been better if we have running code or no code at all.

Honestly, I did not think that a single person would look into this particular notebook, since ARIMA model, in my opinion, is not well suited for this problem. At the moment I do not have a setup for this project in my development environment and, again, do not feel that this notebook is worth fixing, however, if you for some reason still find ARIMA necessary and want to fix this notebook, I would appreciate pull requests.

**Comment by saurabh1396** [comment]
Hello Dziugas,

Could you please help me with the code and the results. I have been stuck
on the similar project for quite a long time. It would be of great help if
you could help me.
